channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10.20

  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=11.8

  - pip
  - pip:
      - timm==1.0.26
      - opencv-python-headless==4.11.0.86
      - pillow
      - tqdm
